### ISSUE TITLE
Americanized app

### ISSUE THREAD

**Issue by drbailey06** [HanSolo/digital#1]
Can you give the option to have miles instead of kilometers and list the date as month,day instead of day,month?

**Comment by HanSolo** [comment]
You should be able to switch between km/miles in the Application settings (either use Garmin Express App or the mobile Garmin Connect app on your phone).
I will add the date format with the next update.

**Comment by HanSolo** [comment]
Added the ability to change the date format between day.month and month/day.
You will find that also in the app settings in either Garmin Express app or the mobile Garmin Connect app.

**Comment by drbailey06** [comment]
Thank you.

**Comment by HanSolo** [comment]
Added some screenshots on how to change the app settings to the README.md file which is shown here: https://github.com/HanSolo/digital
