### ISSUE TITLE
Heartrate and calories display

### ISSUE THREAD

**Issue by krueger17** [HanSolo/digital#5]
Hi, 

Thanks a lot for the layout, I like it. However, if noticed two issues:

1) The heart rate is always unlike the heart rate per the pre-installed Garmin layout (see attached screenshots; your layout shows 72 and the Garmin layout 90, both taken within a few seconds. The difference is not always so large but exists. Is your heart rate perhaps an average or does it have a time lag?
2) At the beginning of the day, the CalorieGoal reached bar at the right starts with a blue bars, even if only very few calories were burnt (see attached: 3 blue bars for 3 calories). Is this correct?

Many thanks for your answer
Regards Bernhard

![20170110_063534](https://cloud.githubusercontent.com/assets/25134580/21963242/8132a3c6-db37-11e6-8d7d-3faf248d7da8.jpg)
![20170110_063545](https://cloud.githubusercontent.com/assets/25134580/21963244/8dccb9e6-db37-11e6-8717-7b915f43236d.jpg)

**Comment by HanSolo** [comment]
Hi there,

I get the heart rate from the Garmin API and I don't update it every second but every minute to save battery. So there is definetely a difference to the live heartrate. The calories are not only the calories burned but the sum of base calories+calories burned. Means if you don't do anything you will see the blue bar rising over day until it's "full". If you are active the blue bar will fill up faster and if you reached your daily calorie base consumption the bar will start again in green. Means from now on you have already burned your daily base calories and all segments green are burned additional. If the green bar filled up completely you burned twice your daily base calories.
Cheers,
Gerrit

**Comment by krueger17** [comment]
Hi Gerrit,

Many thanks for your answers, understood and appreciated. 

Regards
Tom
On 1/15/17, 17:30 Gerrit Grunwald <notifications@github.com> wrote:

  
    
      Hi there,
    
    
      I get the heart rate from the Garmin API and I don't update it every second but every minute to save battery. So there is definetely a difference to the live heartrate. The calories are not only the calories burned but the sum of base calories+calories burned. Means if you don't do anything you will see the blue bar rising over day until it's "full". If you are active the blue bar will fill up faster and if you reached your daily calorie base consumption the bar will start again in green. Means from now on you have already burned your daily base calories and all segments green are burned additional. If the green bar filled up completely you burned twice your daily base calories.
      Cheers,
      Gerrit

**Comment by jltg** [comment]
In my 735xt, the heart rate does not appear on the main screen after the last update.
