### ISSUE TITLE
Mindestumsatz

### ISSUE THREAD

**Issue by krueger17** [HanSolo/digital#8]
Hi, kannst Du mir sagen, wie der Mindestumsatz an Kalorien (rechte Seite) berechnet wird und ob / wie ich den ändern kann? Mir kommt er zu niedrig vor.
Außerdem: Kann ich für die Verwendung des Faces spenden?
Danke

**Comment by HanSolo** [comment]
Hallo,
für die Berechnung des Grundumsatzes verwende ich die Mifflin St. Jeor Formel von 1990. Hier ein Auszug aus Wikipedia zur Berechnung.

Eine neuere Formel wurde 1990 von Mifflin und St.Jeor vorgeschlagen, welche den Lebensstiländerungen der letzten 100 Jahre Rechnung tragen soll und im Mittel ungefähr 5 % akkurater ist (Masse in kg, Größe in cm, Alter in Jahren, Grundumsatz in kcal pro Tag).

G = 10.0 x m + 6.25 x l - 5.0 x t + s.
m = Masse in kg
l = Grösse in cm
t = Alter in Jahren
s = 5 für Männer und -161 für Frauen

Gruß,

Gerrit
