### ISSUE TITLE
Heart rate does not appear

### ISSUE THREAD

**Issue by jltg** [HanSolo/digital#9]
In my 735xt, the heart rate does not appear on the main screen after the last update.

**Comment by N-Parsons** [comment]
I also experienced this bug on my 735xt, but it seems to have been fixed by a recent firmware update (8.30) from Garmin: [change history](https://www8.garmin.com/support/download_details.jsp?id=10060). Heart rate now seems to be displaying correctly on the device.

**Comment by jltg** [comment]
N-Parsons, your answer is correct. Thanks!
